name: staging
description: Staging environment of portfolio app for Sohaib.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.3
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.1

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http: ^1.1.2
  cached_network_image: ^3.3.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  visibility_detector: ^0.4.0+2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/pdfs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
